// <auto-generated />
using BizCraftCrudAP.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BizCraftCrudAP.Migrations
{
    [DbContext(typeof(BizContext))]
    partial class BizContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BizCraftCrudAP.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Facelogo")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Googlogo")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<string>("Linkelogo")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Otherlogo")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Twitlogo")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new { Id = 1, Facelogo = "<i class='fa fa-facebook'></i>", Fullname = "<h3>Vosgi Varduhi</h3>", Googlogo = "<i class='fa fa-google-plus'></i>", Image = "woman1.jpg", Linkelogo = "<i class='fa fa-linkedin'></i>", Otherlogo = "<i class='fa fa-dribbble'></i>", Position = "<p>Web Designer</p>", Twitlogo = "<i class='fa fa-twitter'></i>" },
                        new { Id = 2, Facelogo = "<i class='fa fa-facebook'></i>", Fullname = "<h3>Robert Aleska</h3>", Googlogo = "<i class='fa fa-google-plus'></i>", Image = "man1.jpg", Linkelogo = "<i class='fa fa-linkedin'></i>", Otherlogo = "<i class='fa fa-dribbble'></i>", Position = "<p>Developer</p>", Twitlogo = "<i class='fa fa-twitter'></i>" },
                        new { Id = 3, Facelogo = "<i class='fa fa-facebook'></i>", Fullname = "<h3>Taline Voski</h3>", Googlogo = "<i class='fa fa-google-plus'></i>", Image = "woman2.jpg", Linkelogo = "<i class='fa fa-linkedin'></i>", Otherlogo = "<i class='fa fa-dribbble'></i>", Position = "<p>Graphic Designer</p>", Twitlogo = "<i class='fa fa-twitter'></i>" },
                        new { Id = 4, Facelogo = "<i class='fa fa-facebook'></i>", Fullname = "<h3>Alban Spencer</h3>", Googlogo = "<i class='fa fa-google-plus'></i>", Image = "man22.jpg", Linkelogo = "<i class='fa fa-linkedin'></i>", Otherlogo = "<i class='fa fa-dribbble'></i>", Position = "<p>Junior Developer</p>", Twitlogo = "<i class='fa fa-twitter'></i>" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
